import type { FeatureKey } from "@/features/plans/feature-matrix";

/** Persian display label per feature_key — used by the account page's plan-features list and upgrade prompts. */
export const FEATURE_LABELS: Record<FeatureKey, string> = {
  "menu.core": "منوی دیجیتال QR",
  "menu.profile": "پروفایل کسب‌وکار",
  "menu.multilang": "منوی دوزبانه",
  "menu.custom_theme": "شخصی‌سازی ظاهر منو",
  "menu.qr_export": "خروجی QR کد",
  "menu.reviews_display": "نمایش نظرات مشتریان",
  "domain.subdomain": "آدرس اختصاصی زیردامنه",
  "domain.custom": "دامنه اختصاصی",
  "branch.count": "تعداد شعبه",
  "branch.multi_switcher": "سوییچ بین چند شعبه",
  "support.ticketing": "پشتیبانی تیکتینگ",
  "product.crud": "مدیریت محصولات",
  "product.variants": "گزینه‌های محصول (سایز، افزودنی و…)",
  "product.inventory": "پیگیری موجودی",
  "staff.roles": "مدیریت کاربران و نقش‌ها",
  "category.schedule": "زمان‌بندی نمایش دسته‌بندی",
  "order.notes": "یادداشت سفارش",
  "order.three_mode": "سفارش‌گیری (روی میز، بیرون‌بر، پیک)",
  "order.manual_entry": "ثبت سفارش دستی",
  "discount.manual_auto": "تخفیف‌های دستی و خودکار",
  "review.submit_survey": "نظرسنجی بعد از سفارش",
  "report.menu_visits": "گزارش بازدید منو",
  "report.orders": "گزارش سفارشات",
  "printer.connection": "اتصال پرینتر",
  "loyalty.cashback": "کش‌بک باشگاه مشتریان",
  "loyalty.birthday_message": "پیام تولد",
  "loyalty.targeted_message": "ارسال پیام هدفمند",
  "customer.export": "خروجی اکسل مشتریان",
  "customer.wallet_login": "کیف پول و ورود مشتری",
  "payment.gateway": "درگاه پرداخت آنلاین",
  "sms.panel": "پنل پیامک",
  "delivery.internal_riders": "مدیریت پیک‌های داخلی",
  "accounting.simple": "حسابداری ساده",
};
