-- Seed PlanFeature from features/plans/feature-matrix.ts (the single source
-- of truth for what each plan includes). This runs as a real migration, not
-- prisma/seed.ts, because prisma/seed.ts is never invoked on deploy — only
-- `prisma migrate deploy` runs (see Dockerfile CMD) — so PlanFeature was
-- coming up empty after every redeploy while Plan itself stayed populated.
-- Idempotent (ON CONFLICT DO UPDATE) so it's safe to have already run by
-- hand once and safe to run again on the next deploy.
INSERT INTO "PlanFeature" ("id", "planId", "featureKey", "limitValue")
SELECT
  md5(random()::text || clock_timestamp()::text),
  p.id,
  v.feature_key,
  v.limit_value::text
FROM "Plan" p
JOIN (VALUES
  ('menu-display', 'menu.core', NULL),
  ('menu-order', 'menu.core', NULL),
  ('menu-advanced', 'menu.core', NULL),
  ('menu-display', 'menu.profile', NULL),
  ('menu-order', 'menu.profile', NULL),
  ('menu-advanced', 'menu.profile', NULL),
  ('menu-display', 'menu.multilang', NULL),
  ('menu-order', 'menu.multilang', NULL),
  ('menu-advanced', 'menu.multilang', NULL),
  ('menu-display', 'menu.custom_theme', NULL),
  ('menu-order', 'menu.custom_theme', NULL),
  ('menu-advanced', 'menu.custom_theme', NULL),
  ('menu-display', 'menu.qr_export', NULL),
  ('menu-order', 'menu.qr_export', NULL),
  ('menu-advanced', 'menu.qr_export', NULL),
  ('menu-display', 'menu.reviews_display', NULL),
  ('menu-order', 'menu.reviews_display', NULL),
  ('menu-advanced', 'menu.reviews_display', NULL),
  ('menu-display', 'domain.subdomain', NULL),
  ('menu-order', 'domain.subdomain', NULL),
  ('menu-advanced', 'domain.subdomain', NULL),
  ('menu-display', 'product.crud', NULL),
  ('menu-order', 'product.crud', NULL),
  ('menu-advanced', 'product.crud', NULL),
  ('menu-display', 'staff.roles', NULL),
  ('menu-order', 'staff.roles', NULL),
  ('menu-advanced', 'staff.roles', NULL),
  ('menu-display', 'category.schedule', NULL),
  ('menu-order', 'category.schedule', NULL),
  ('menu-advanced', 'category.schedule', NULL),
  ('menu-display', 'order.notes', NULL),
  ('menu-order', 'order.notes', NULL),
  ('menu-advanced', 'order.notes', NULL),
  ('menu-display', 'report.menu_visits', NULL),
  ('menu-order', 'report.menu_visits', NULL),
  ('menu-advanced', 'report.menu_visits', NULL),
  ('menu-display', 'branch.count', '1'),
  ('menu-order', 'branch.count', '1'),
  ('menu-advanced', 'branch.count', '3'),
  ('menu-display', 'support.ticketing', 'ticketing'),
  ('menu-order', 'support.ticketing', 'ticketing'),
  ('menu-advanced', 'support.ticketing', 'ticketing+phone'),
  ('menu-order', 'domain.custom', NULL),
  ('menu-advanced', 'domain.custom', NULL),
  ('menu-order', 'order.three_mode', NULL),
  ('menu-advanced', 'order.three_mode', NULL),
  ('menu-order', 'product.variants', NULL),
  ('menu-advanced', 'product.variants', NULL),
  ('menu-order', 'product.inventory', NULL),
  ('menu-advanced', 'product.inventory', NULL),
  ('menu-order', 'discount.manual_auto', NULL),
  ('menu-advanced', 'discount.manual_auto', NULL),
  ('menu-order', 'order.manual_entry', NULL),
  ('menu-advanced', 'order.manual_entry', NULL),
  ('menu-order', 'review.submit_survey', NULL),
  ('menu-advanced', 'review.submit_survey', NULL),
  ('menu-order', 'report.orders', NULL),
  ('menu-advanced', 'report.orders', NULL),
  ('menu-order', 'loyalty.cashback', NULL),
  ('menu-advanced', 'loyalty.cashback', NULL),
  ('menu-order', 'customer.export', NULL),
  ('menu-advanced', 'customer.export', NULL),
  ('menu-order', 'customer.wallet_login', NULL),
  ('menu-advanced', 'customer.wallet_login', NULL),
  ('menu-order', 'payment.gateway', NULL),
  ('menu-advanced', 'payment.gateway', NULL),
  ('menu-order', 'printer.connection', '2'),
  ('menu-advanced', 'printer.connection', 'unlimited'),
  ('menu-advanced', 'loyalty.birthday_message', NULL),
  ('menu-advanced', 'loyalty.targeted_message', NULL),
  ('menu-advanced', 'sms.panel', NULL),
  ('menu-advanced', 'branch.multi_switcher', NULL),
  ('menu-advanced', 'delivery.internal_riders', NULL),
  ('menu-advanced', 'accounting.simple', NULL)
) AS v(plan_key, feature_key, limit_value) ON v.plan_key = p.key
ON CONFLICT ("planId", "featureKey") DO UPDATE SET "limitValue" = EXCLUDED."limitValue";
