-- AlterTable
ALTER TABLE "Business" ADD COLUMN     "prepTimeDelivery" INTEGER NOT NULL DEFAULT 45,
ADD COLUMN     "prepTimeDineIn" INTEGER NOT NULL DEFAULT 15,
ADD COLUMN     "prepTimeTakeaway" INTEGER NOT NULL DEFAULT 20,
ADD COLUMN     "qrShowHours" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "qrShowInfo" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "qrShowLogo" BOOLEAN NOT NULL DEFAULT true;

